import shutil
import tempfile
import unittest
from pathlib import Path

from src.qgis_manager.core import get_rcc_tool, patch_resource_file


class TestRCCModernization(unittest.TestCase):
    def setUp(self):
        self.test_dir = Path(tempfile.mkdtemp())

    def tearDown(self):
        shutil.rmtree(self.test_dir)

    def test_get_rcc_tool(self):
        tool = get_rcc_tool()
        # On this system we know pyrcc5 is available
        self.assertIn(tool, ["pyside6-rcc", "pyside2-rcc", "pyrcc5"])

    def test_patch_resource_file(self):
        py_file = self.test_dir / "resources_rc.py"
        content = """# Generated by pyrcc5
import resources_rc
import other_rc

class UI:
    pass
"""
        py_file.write_text(content)

        patched = patch_resource_file(py_file)
        self.assertTrue(patched)

        new_content = py_file.read_text()
        self.assertIn("from . import resources_rc", new_content)
        self.assertIn("from . import other_rc", new_content)
        self.assertNotIn("\nimport resources_rc", new_content)

    def test_patch_resource_file_no_change(self):
        py_file = self.test_dir / "clean.py"
        content = "print('hello')"
        py_file.write_text(content)

        patched = patch_resource_file(py_file)
        self.assertFalse(patched)
        self.assertEqual(py_file.read_text(), content)


if __name__ == "__main__":
    unittest.main()
